title: Mwende Mutuku's Portfolio
logo: "https://raw.githubusercontent.com/MutukuMwende/Portfolio/main/photo.png"
Description: A showcase of my projects and skills.
show_downloads: true

url: "https://github.com/MutukuMwende/Portfolio" 

author:
  name: "Mwende Mutuku"
  email: "claremwnde99@gmail.com" 
  bio: "Pharmacist | Data Scientist | Researcher"


theme: jekyll-theme-minimal

social_links:
  github: "https://github.com/MwendeMutuku"  
  linkedin: "https://linkedin.com/in/mwende-mutuku"  
  email: "claremwende99@gmail.com" 
