title: Mwende Mutuku's Portfolio
logo: /"C:\Users\Hp\Documents\PROJECTS\Assets\Headshot.jpeg"
Description: A showcase of my projects and skills.
show_downloads: true

url: "https://github.com/MutukuMwende/Portfolio" 

author:
  name: "Mwende Mutuku"
  email: "claremwnde99@gmail.com" 
  bio: "Pharmacist | Data Scientist | Researcher"
Dedicated to advancing digital health through data science and AI-driven approaches to innovate and transform healthcare systems

theme: jekyll-theme-minimal


social_links:
  github: "https://github.com/MwendeMutuku"  
  linkedin: "https://linkedin.com/in/mwende-mutuku"  
  email: "claremwende99@gmail.com" 
